channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python==3.7
  - pip
  - python-dotenv
  - scikit-learn
  - numpy
  - scipy
  - matplotlib
  - pandas
  - sympy
  - nose
  - seaborn
  - joblib
  - requests